/**
 * Stripe Service Factory
 *
 * Returns either the real Stripe API client or the mock implementation,
 * depending on whether STRIPE_SECRET_KEY is configured.
 *
 * Usage:
 *   import { getStripeService } from '@suiftly/database/stripe-mock';
 *   const stripeService = getStripeService();
 */

import type {
  IStripeService,
  StripeChargeParams,
  StripeChargeResult,
  StripePaymentMethod,
  StripeRefundParams,
  StripeRefundResult,
} from '@suiftly/shared/stripe-service';
import { StripeService } from '../stripe-service/stripe-service.js';
import { mockStripeService } from './mock.js';

export { stripeMockConfig } from './mock-config.js';
export type { StripeMockConfig } from './mock-config.js';
export { MockStripeService, mockStripeService } from './mock.js';

/** Cached real service instance (created once, reused) */
let realStripeService: IStripeService | null = null;

/** When true, getStripeService() returns mock regardless of STRIPE_SECRET_KEY */
let forceMock = false;

/**
 * Proxy that automatically routes mock IDs to the mock service and real IDs
 * to the real Stripe service.
 *
 * Problem it solves: in dev/test mode, the API and GM are separate processes.
 * The API creates mock Stripe customers (cus_mock_*) in its in-memory mock.
 * The GM runs in a separate process with its own Stripe service instance.
 * Without this proxy, GM would try to charge cus_mock_* on real Stripe → fail.
 *
 * With this proxy, any ID that looks like a mock ID is automatically routed to
 * the in-memory mock service, regardless of which process calls it.
 *
 * In production, no mock IDs exist (they start with cus_mock_), so all calls
 * pass through to real Stripe with zero overhead.
 */
class AutoDetectStripeProxy implements IStripeService {
  constructor(private real: IStripeService) {}

  /** True if the ID was generated by the mock service */
  private isMockId(id: string): boolean {
    return (
      id.startsWith('cus_mock_') ||
      id.startsWith('pm_mock_') ||
      id.startsWith('in_mock_') ||
      id.startsWith('seti_mock_') ||
      id.startsWith('pi_mock_') ||
      id.startsWith('re_mock_')
    );
  }

  private pick(id: string): IStripeService {
    return this.isMockId(id) ? mockStripeService : this.real;
  }

  createCustomer(params: { customerId: number; walletAddress: string; email?: string }) {
    return this.real.createCustomer(params);
  }

  createSetupIntent(stripeCustomerId: string) {
    return this.pick(stripeCustomerId).createSetupIntent(stripeCustomerId);
  }

  charge(params: StripeChargeParams): Promise<StripeChargeResult> {
    return this.pick(params.stripeCustomerId).charge(params);
  }

  getPaymentMethods(stripeCustomerId: string): Promise<StripePaymentMethod[]> {
    return this.pick(stripeCustomerId).getPaymentMethods(stripeCustomerId);
  }

  deletePaymentMethod(paymentMethodId: string): Promise<void> {
    return this.pick(paymentMethodId).deletePaymentMethod(paymentMethodId);
  }

  setDefaultPaymentMethod(stripeCustomerId: string, paymentMethodId: string): Promise<void> {
    return this.pick(stripeCustomerId).setDefaultPaymentMethod(stripeCustomerId, paymentMethodId);
  }

  refund(params: StripeRefundParams): Promise<StripeRefundResult> {
    return this.pick(params.stripeInvoiceId).refund(params);
  }

  voidInvoice(stripeInvoiceId: string): Promise<{ success: boolean; error?: string }> {
    return this.pick(stripeInvoiceId).voidInvoice(stripeInvoiceId);
  }

  isMock(): boolean {
    return false;
  }
}

/** Cached proxy instance (wraps the real service, created once) */
let autoDetectProxy: AutoDetectStripeProxy | null = null;

/**
 * Get Stripe service instance.
 *
 * Selection logic:
 * - If forceMock is set (via test endpoint) → mock
 * - If STRIPE_SECRET_KEY is set and non-empty → AutoDetectStripeProxy wrapping real Stripe.
 *   The proxy routes mock IDs (cus_mock_*, pm_mock_*, etc.) to the in-memory mock service
 *   and all other IDs to real Stripe. This allows GM and API to handle both real and mock
 *   customers without explicit force-mock coordination between processes.
 * - Otherwise → mock (in-memory, for development without a Stripe key)
 */
export function getStripeService(): IStripeService {
  if (forceMock) {
    return mockStripeService;
  }

  const secretKey = process.env.STRIPE_SECRET_KEY;

  if (secretKey && secretKey.length > 0) {
    if (!realStripeService) {
      realStripeService = new StripeService(secretKey);
      console.log('[STRIPE] Using real Stripe service (API key configured)');
    }
    if (!autoDetectProxy) {
      autoDetectProxy = new AutoDetectStripeProxy(realStripeService);
    }
    return autoDetectProxy;
  }

  return mockStripeService;
}

/**
 * Force mock mode for tests. When true, getStripeService() returns
 * MockStripeService even if STRIPE_SECRET_KEY is configured.
 */
export function setStripeForceMock(value: boolean): void {
  forceMock = value;
  if (value) {
    console.log('[STRIPE] Force-mock mode enabled (tests)');
  } else {
    console.log('[STRIPE] Force-mock mode disabled');
  }
}

/** Check if force-mock mode is active (used by config endpoint to hide publishable key). */
export function isStripeForceMock(): boolean {
  return forceMock;
}

/**
 * Reset the cached real service instance.
 * Only needed for tests that switch between real and mock.
 */
export function resetStripeServiceCache(): void {
  realStripeService = null;
  autoDetectProxy = null;
}

/**
 * Re-export types for convenience
 */
export type {
  IStripeService,
  StripeChargeParams,
  StripeChargeResult,
  StripePaymentMethod,
  StripeRefundParams,
  StripeRefundResult,
} from '@suiftly/shared/stripe-service';
