/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletDemoRouteImport } from './routes/wallet-demo'
import { Route as IndexRouteImport } from './routes/index'

const WalletDemoRoute = WalletDemoRouteImport.update({
  id: '/wallet-demo',
  path: '/wallet-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wallet-demo': typeof WalletDemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/wallet-demo': typeof WalletDemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wallet-demo': typeof WalletDemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/wallet-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/wallet-demo'
  id: '__root__' | '/' | '/wallet-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WalletDemoRoute: typeof WalletDemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet-demo': {
      id: '/wallet-demo'
      path: '/wallet-demo'
      fullPath: '/wallet-demo'
      preLoaderRoute: typeof WalletDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WalletDemoRoute: WalletDemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
